# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(size=(7, 7))
random_tensor

tensor([[0.0048, 0.2376, 0.5615, 0.4071, 0.9137, 0.4539, 0.6377],
        [0.9168, 0.3626, 0.8533, 0.1380, 0.5158, 0.8273, 0.7840],
        [0.6665, 0.7476, 0.5919, 0.6701, 0.5017, 0.5148, 0.5670],
        [0.2073, 0.7842, 0.1495, 0.7392, 0.1069, 0.1922, 0.0644],
        [0.2956, 0.1616, 0.9765, 0.0585, 0.3810, 0.5276, 0.4729],
        [0.6829, 0.3088, 0.2173, 0.2029, 0.6626, 0.9245, 0.4556],
        [0.3638, 0.4153, 0.6239, 0.5733, 0.5789, 0.5458, 0.4972]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
random_tensor_2 = torch.rand(size=(1, 7))
# Perform matrix multiplication
matmul_tensor = torch.matmul(random_tensor, random_tensor_2.T)
matmul_tensor

tensor([[1.1686],
        [2.1213],
        [1.6854],
        [0.7252],
        [1.3549],
        [1.7997],
        [1.4391]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensor = torch.rand(size=(7, 7))
random_tensor_2 = torch.rand(size=(1, 7))

# Matrix multiply tensors
matmul_tensor = torch.matmul(random_tensor, random_tensor_2.T)
matmul_tensor

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [11]:
matmul_tensor.size()


torch.Size([7, 1])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [12]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [15]:
# Set random seed
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available
torch.manual_seed(1234)
random_tensor = torch.rand(size=(2, 3)).to(device)
random_tensor_2 = torch.rand(size=(2, 3)).to(device)
matmul_tensor = torch.matmul(random_tensor, random_tensor_2.T)
matmul_tensor

# Check for access to GPU

# Create two random tensors on GPU


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [18]:
matmul_tensor

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [19]:
# Find max
torch.max(matmul_tensor)
# Find min
torch.min(matmul_tensor)

tensor(0.3647, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [20]:
# Find arg max
torch.argmax(matmul_tensor)

# Find arg min
torch.argmin(matmul_tensor)

tensor(0, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [21]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
squeezed_tensor = torch.squeeze(random_tensor)

# Print out tensors and their shapes
random_tensor, random_tensor.shape, squeezed_tensor, squeezed_tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))